name: run test

on:
    push:
        branches: [ main ]

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v3

            -   id: auth
                name: Authentication phase
                uses: google-github-actions/auth@v0
                with:
                    credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

#            -   name: Checkout Repo
#                uses: actions/checkout@v2
#
#            -   name: Set up Python 3.9
#                uses: actions/setup-python@v3
#                with:
#                    python-version: 3.9
#
#            -   id: auth
#                name: Authenticate to Google Cloud
#                uses: google-github-actions/auth@v0.4.0
#                with:
#                    workload_identity_provider: projects/69420/locations/global/workloadIdentityPools/my-pool/providers/my-provider
#                    service_account: github-x-google@youtube-automatic-playlists.iam.gserviceaccount.com
#
#            -   id: gcloud
#                name: gcloud
#                run: |-
#                    gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
#                    gcloud services list
#
##      - name: Install Python Packages
##        run: |
##          python -m pip install --upgrade pip
##          pip install -r requirements.txt
##
##      - name: Lint with flake8
##        run: |
##          pip install flake8
##          # Stop the build if there are Python syntax errors or undefined names
##          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
##          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
##          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#
##      - name: _test.py execution
##        run: |
##          cd src
##          python _test.py
##          cd ../
##
##      - name: Commit files
##        id: commit
##        run: |
##          git config --local user.email "action@github.com"
##          git config --local user.name "github-actions"
##          git add --all
##          git commit -m "Commit changes"
##
##      - name: Push changes
##        uses: ad-m/github-push-action@master
##        with:
##          github_token: ${{ secrets.GITHUB_TOKEN }}
##          force: true