name: run test

on:
    push:
        branches: [main]

jobs:
    build-linux:
        name: Automation environment
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            -   id: checkout
                name: Checkout repository
                uses: actions/checkout@v3

            -   id: google-auth
                name: Authentication to Google Cloud services with Workload Identity Federation
                uses: google-github-actions/auth@v0
                with:
                    token_format: 'access_token'
                    access_token_scopes: 'https://www.googleapis.com/auth/youtube.force-ssl'
                    workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
                    service_account: '${{ secrets.SERVICE_ACCOUNT }}'

            -   id: python-setup
                name: Set up Python 3.9
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9

            -   id: dependencies
                name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   id: flake8
                name: Lint with flake8
                run: |
                    pip install flake8
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            -   id: test
                name: Test / _test.py execution
                run: |
                    cd src
                    python _test.py 'action'
                    cd ../