name: run test

on:
    push:
        branches: [ main ]

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            -   id: checkout
                name: Checkout repository.
                uses: actions/checkout@v3

            -   id: google-auth
                name: Authentication to Google Cloud services from repository's SECRETS.
                uses: google-github-actions/auth@v0
                with:
                    create_credentials_file: true
                    credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
                    cleanup_credentials: true

            -   name: Set up Python 3.9
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9