name: Adjust updates schedule

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'

    schedule:
        -   cron: '0 6 * * *' # Starting @ 06:00 AM everyday

jobs:
    build-linux:
        name: cron_adjustment
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write

        steps:
            -   id: checkout
                name: Checkout repository
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.PAT }}

            -   id: python-setup
                name: Set up Python 3.10
                uses: actions/setup-python@v5
                with:
                    python-version: 3.10

            -   id: dependencies
                name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   id: flake8
                name: Lint with flake8
                run: |
                    pip install flake8
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            -   id: cron_update
                name: cron_update.py execution
                run: |
                    cd src
                    python cron_update.py
                    cd ../

            -   id: check_dff
                name: Check if differences after cron_update run
                run: |
                    if [[ "$(git diff --exit-code)" =~ 'diff' ]]; then 
                        echo "IS_VALID=true" >> $GITHUB_ENV; 
                    else 
                        echo "IS_VALID=false" >> $GITHUB_ENV ;
                    fi

            -   id: commit
                name: Commit changes
                if: ${{ env.IS_VALID == 'true' }}
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "github-actions"
                    git commit -m "ci(.github): Schedule for Playlists Updates adjusted." -a

            -   id: push
                name: Push changes
                if: ${{ env.IS_VALID == 'true' }}
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.PAT }}
                    force: true
