name: Adjust updates schedule

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'

    schedule:
        -   cron: '0 6 * * 0' # 06:00 AM every Sunday

jobs:
    build-linux:
        name: cron_adjustment
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write

        steps:
            -   id: checkout
                name: Checkout repository
                uses: actions/checkout@v3
                with:
                    token: ${{ secrets.PAT }}

            -   id: python-setup
                name: Set up Python 3.9
                uses: actions/setup-python@v4
                with:
                    python-version: 3.9

            -   id: dependencies
                name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   id: flake8
                name: Lint with flake8
                run: |
                    pip install flake8
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            -   id: cron_update
                name: cron_update.py execution
                run: |
                    cd src
                    python cron_update.py
                    cd ../

            -   id: commit
                name: Commit changes
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "github-actions"
                    git commit -m "ci(.github): Schedule for Playlists Updates adjusted." -a

            -   id: push
                name: Push changes
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.PAT }}
                    force: true