name: Update LICENCE years

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'

    schedule:
        -   cron: '0 1 1 1 *' # 01:00 AM on January 1

jobs:
    update-license-year:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   uses: FantasticFiasco/action-update-license-year@v3
                with:
                    token: ${{ secrets.PAT }}