name: Test - Repository Secret Update

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'

jobs:
    build-linux:
        name: repo-secret-update
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write

        env:
            GITHUB_REPOSITORY: '${{ github.GITHUB_REPOSITORY }}'
            PAT: '${{ secrets.PAT }}'

        steps:
            -   id: checkout
                name: Checkout repository
                uses: actions/checkout@v3

            -   id: python-setup
                name: Set up Python 3.9
                uses: actions/setup-python@v4
                with:
                    python-version: 3.9

            -   id: dependencies
                name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   id: flake8
                name: Lint with flake8
                run: |
                    pip install flake8
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            -   id: _sandbox
                name: _sandbox.py execution
                run: |
                    cd src
                    python _sandbox
                    cd ../
